// Peticiones Clients -----------------

GET http://localhost:3000/api/clients

###
POST http://localhost:3000/api/clients/new
Content-Type: application/json

{
    "nombre": "JUAN2",
    "apellidos": "AGUILARTE2",
    "direccion": "CALLE2",
    "telefono": "666662",
    "fecha_nacimiento": null,
    "dni": "22222",
    "email": "DSDSSD@DSSD.COM22"
}
###
PUT http://localhost:3000/api/clients/edit/13
Content-Type: application/json

{
    "nombre": "JUAN2 - Actualizado",
    "apellidos": "AGUILARTE2",
    "direccion": "CALLE2",
    "telefono": "666662",
    "fecha_nacimiento": null,
    "dni": "22222",
    "email": "DSDSSD@DSSD.COM22"
}
### 
DELETE http://localhost:3000/api/clients/delete/12

# PETICIONE VIAJES --------------------

###
GET http://localhost:3000/api/travels

###
POST http://localhost:3000/api/travels/new/5
Content-Type: application/json

{
    "fecha_salida": "2022/12/12", 
    "fecha_vuelta": "2022/12/13", 
    "id_vuelo_ida": 3, 
    "id_vuelo_vuelta": 3,
    "hotel_id": 1
}

###
PUT http://localhost:3000/api/travels/edit/5
Content-Type: application/json

{
"fecha_salida": "2022/12/12",
"fecha_vuelta": "2022/12/13",
"id_vuelo_ida": 5,
"id_vuelo_vuelta": 4,
"hotel_id": 10
}

### 
DELETE http://localhost:3000/api/travels/delete/7

# PETICIONE HOTELES --------------------

###
GET http://localhost:3000/api/hotels

###
POST http://localhost:3000/api/hotels/new
Content-Type: application/json

{
    "nombre": "Hotel1", 
    "direccion": "Direccion1", 
    "ciudad": "Ciudad1", 
    "num_estrellas": 4, 
    "descripcion": "descripcion 1",
    "tarifa": 30
}

###
PUT http://localhost:3000/api/hotels/edit/3
Content-Type: application/json

{
    "nombre": "Hotel - Cambiado", 
    "direccion": "Direccion1 - Cambiado", 
    "ciudad": "Ciudad1  - Cambiado", 
    "num_estrellas": 4, 
    "descripcion": "descripcion 1  - Cambiado",
    "tarifa": 30
}

### 
DELETE http://localhost:3000/api/hotels/delete/2


###
POST http://localhost:3000/api/clients/5/travel/4